# -*- coding: utf-8 -*-
"""streamlitdeployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-5PvIJw5LyNDIFWk_bz6UQM5OIybkdG
"""


import tensorflow as tf
from tensorflow import keras
import streamlit as st
model_gru=keras.models.load_model("model fix/model_gru")

model_gru.summary()

import pickle
with open("tokenizer.pickle", 'rb') as handle:
    b = pickle.load(handle)



st.title('Lazada TextReview-Rating Predictor')
text=st.text_input('Masukan Review Disini')
def predict(text):
    text=str(text)
    text=[text]
    token_matrix=b.texts_to_sequences(text)
    token_sequence=keras.preprocessing.sequence.pad_sequences(token_matrix,padding='post',maxlen=361)
    pre=model_gru.predict(token_sequence)
    global x1
    for i,j in enumerate(pre.T,1):
      if j==pre.max():
        x1=(f'Rating:{i}',f'Prob:{str(j)}')
    return x1
if st.button('Predict Rating'):
    hasil=predict(text)
    st.write(x1)
    
    





